алгоритмы балакирев гит хаб  
https://github.com/selfedu-rus/python-algorithms/tree/master

если мы вставляем или удаляем элемент с конца списка, то сложность O(1)  
но если мы вставляем в начало или удаляем с начала, то сложность O(n)  
так как после удаления или перед вставкой нужно сдвинуть элементы,  
поэтому так лучше не делать, либо добавлять и удалять с конца,  
либо использовать очередь, например deque

In [6]:
l = [1,2,3,4,5]
# так норм
l.append(3)
l.pop()
# но так будет медленно
l.insert(0, 3)
l.pop(0)

3

Queue on python

In [ ]:
from collections import deque

dq = deque(range(1, 10))
dq.append(12)
dq.appendleft(-1)
try:
    dq.pop()
    dq.popleft()
except IndexError as ex:
    print(ex)
dq.extend([22, 33, 44])
dq.extendleft([-11, -22])
dq.insert(-3, 3)
dq.remove(3)

# FIFO
dq.append(4)
dq.popleft()
# or
dq.appendleft(4)
dq.pop()
# LIFO
dq.append(4)
dq.pop()
# or
dq.appendleft(4)
dq.popleft()

print(dq)

Stack on python

In [4]:
from collections import deque

stack = deque()

stack.append(7)
stack.append(5)
print(stack)
stack.pop()
print(stack)
stack.append(11)
print(stack)

deque([7, 5])
deque([7])
deque([7, 11])


Binary tree

In [24]:
class Node:
    def __init__(self, data) -> None:
        self.data = data
        self.left = self.right = None
class Tree:
    def __init__(self) -> None:
        self.root = None
        
    def __find(self, node, parent, value):
        if node is None:
            return None, parent, False
        if value == node.data:
            return node, parent, True
        if value < node.data:
            if node.left:
                return self.__find(node.left, node, value)
            
        if value > node.data:
            if node.right:
                return self.__find(node.right, node, value)     
         
        return node, parent, False
                   
    def append(self, obj: Node):
        if self.root is None:
            self.root = obj
            return obj
        s, p, fl_find = self.__find(self.root, None, obj.data)
        if not fl_find and s:
            if obj.data < s.data:
                s.left = obj
            else:
                s.right = obj
        return obj
    def show_tree(self, node):
        if node is None:
            return
        self.show_tree(node.left)
        print(node.data)
        self.show_tree(node.right)
    def show_wide_tree(self, node):
        if node is None:
            return
        lv = [node]
        while lv:
            l = []
            for node in lv:
                print(node.data, end=' ')
                if node.left:
                    l.append(node.left)
                if node.right:
                    l.append(node.right)
            print()
            lv = l
        
    def __del_leaf(self, node, parent):
        if node == parent.left:
            parent.left = None
        elif node == parent.right:
            parent.right = None        
    
    def __del_one_child(self, node, parent):
        if node == parent.left:
            if node.left is None:
                parent.left = node.right
            elif node.right is None:
                parent.right = node.right      
        elif node == parent.right:
            if node.left is None:
                parent.right = node.right
            elif node.right is None:
                parent.right = node.right   
                
    def __find_min(self, node, parent):
        if node.left:
            return self.__find_min(node.left, node)
        else:
            return node, parent
        
                                
    def del_node(self, value):
        s, p, fl_find = self.__find(self.root, None, value)
        if not fl_find:
            return None
        if s.left is None and s.right is None:
            self.__del_leaf(s, p)      
        elif s.left is None or s.right is None:
            self.__del_one_child(s, p)
        elif s.left is not None and s.right is not None:
            sr, pr = self.__find_min(s.right, s)
            s.data = sr.data
            self.__del_one_child(sr, pr)
        
        
v = [44, 22, 1, 6, 4, 2, 7, 33]

tree = Tree()
for el in v:
    tree.append(Node(el))
tree.show_tree(tree.root)
tree.del_node(6)
print()
tree.show_tree(tree.root)
print()
tree.show_wide_tree(tree.root)

1
2
4
6
7
22
33
44

1
2
4
7
22
33
44

44 
22 
1 33 
7 
4 
2 


Прямой поиск подстроки в строке  
имеет сложность O(n * m)

In [8]:
s = 'in this ddaya'
sf = 'day'
match = 0
start = -1
for i in range(len(s) - len(sf) + 1):
    for j in range(len(sf)):
        if s[i+j] != sf[j]:
            break
    else:
        match = 1
    if match == 1:
        start = i
        break
start

9

Алгоритм Рабина Карпа

Суть простая,  мы считаем хэш патерна и участка строки размером с патерн и сравниваем хэши,  
хэши можно считать через систему счисления размером с алфавит  
если хэши не совпали, то смещаемся в тексте на одни символ и повторяем  
по сути это обычный поиск перебором, но за счет хэшей, мы ускоряемся, так как не нужно сравнивать поэлементно,  
если хэши не совпали  

In [49]:
# Подходит для небольшого алфавита  
# Нумеруем все буквы числами
# если букв больше 9, то можно использовать шестнадцатиричные числа, чтобы меньше переполнять память,  
# так как если мы будем увеличивать код числа дальше после 9, то у нас будет основание расти и будет возводиться в степерь и будет переполнение  
d = {'a': 1, 'b': 2, 'c': 3, 'd': 4, ' ': 1}
base = 5
# hash(list) = d[list[0]] * base ^ (n-1) + d[list[1]] * base ^ (n-2) + ... + d[list[n-1]] * base ^ 0
def my_hash(l, d):
    base = len(d)
    res = 0
    n = len(l)
    for i in range(n):
        res += d[l[i]] * base ** (n-1-i)
    return res
text = 'abc abcad dabcb'
pattern = 'abc'
text_n = len(text)
pattern_n = len(pattern)
pattern_hash = my_hash(pattern, d)
find = []
for i in range(text_n):
    text_for_compare = text[i:i+pattern_n]
    if my_hash(text_for_compare, d) != pattern_hash:
        continue
    else:
        for j in range(pattern_n):
            if text[i + j] != pattern[j]:
                break
        else:
            find.append(i)
find

[0, 4, 11]

Алгоритм Кнута-Морриса-Пратта (КМП-алгоритм)  
поиск подстроки в строке 

In [23]:
# сначала найдем массив суффиксов
s = 'бобо'
j = 0
i =1
res = [0] * len(s)
while i < len(s):
    if s[j] != s[i]:
        if j == 0:
            res[i] = 0
            i += 1
        else:
# это самое сложное место
# это гениальное решение авторов алгоритма,
# если у нас есть совпадения суфикса и префикса
# и на каком то символе совпадение заканчивается, 
# то мы i не изменяем, так как нужно будет продолжить сравнение с этого символа
# а j устанавливаем на место, где было начало совпадения префикса для текущей позиции j, 
# то есть если у нас сейчас j = 2, то нам нужно взять из нашего результирующего массива
# значнеие по индексу j - 1, там как раз хранится длинна префикса           
            j = res[j - 1]
    else:
        res[i] = j + 1
        j += 1
        i += 1
s1 = 'дом лес озеро небобобо'   
i = 0
j = 0
find = 0
while i < len(s1):
    if s1[i] == s[j]:
        i += 1
        j += 1
        if j == len(s):
            find = 1
            break
    else:
        if j > 0:
            j = res[j-1]
        else:
            i += 1
find
    
    
    
    
    

1

Алгоритм Бойера-Мура-Хорспула  
поиск подстроки в строке 

In [9]:
s = 'большие метеоданные'
a = 'данные'
inv_a = a[::-1]
indx = dict()
for i in range(1, len(inv_a)):
    if inv_a[i] not in indx:
        indx[inv_a[i]] = i
if a[-1] not in indx:
    indx[a[-1]] = len(a)
indx['*'] = len(a)
            
indx

{'ы': 1, 'н': 2, 'а': 4, 'д': 5, 'е': 6, '*': 6}

In [10]:
cur = len(a) - 1
find = 0
while cur < len(s):
    j = len(a) - 1
    i = cur
    while j >= 0:
        if s[i] != a[j]:
            if j == len(s):
                cur += indx['*']
            else:
                cur += indx[a[j]]
            break
        else:
            if j == 0:
                find = 1
                break
            else:
                j -= 1
                i -= 1
    if find:
        break
find            
        


1

Алгоритм Дейкстры

In [84]:
import numpy as np
d = np.array(((0, 3, 1, 3, 0, 0), 
     (3, 0, 4, 0, 0, 0), 
     (1, 4, 0, 0, 7, 5), 
     (3, 0, 0, 0, 0, 2), 
     (0, 0, 7, 0, 0, 4), 
     (0, 0, 5, 2, 4, 0))
)

n = len(d)
t = np.array([np.inf]*n)
step = [0, ] * n
i = 0
t[i] = 0
my_i = 0
step[i] = 1
while not all(step):
     temp = np.array([x if x != 0 else np.inf for x in d[i]])
     temp += t[i]
     t = np.min([t, temp], axis=0)   
     find = 0
     temp = t.copy()
     while not find:
          i = temp.argmin()
          if step[i]:
               temp[i] = np.inf
          else:
               find = 1
     print(step)
     print(temp)
     print(t)
     print(i)
     step[i] = 1
     

[1, 0, 0, 0, 0, 0]
[inf  3.  1.  3. inf inf]
[ 0.  3.  1.  3. inf inf]
2
[1, 0, 1, 0, 0, 0]
[inf  3. inf  3.  8.  6.]
[0. 3. 1. 3. 8. 6.]
1
[1, 1, 1, 0, 0, 0]
[inf inf inf  3.  8.  6.]
[0. 3. 1. 3. 8. 6.]
3
[1, 1, 1, 1, 0, 0]
[inf inf inf inf  8.  5.]
[0. 3. 1. 3. 8. 5.]
5
[1, 1, 1, 1, 0, 1]
[inf inf inf inf  8. inf]
[0. 3. 1. 3. 8. 5.]
4


Алгоритм Флойда

In [2]:
import numpy as np

def find_path(p, start, end):
    path = [start]
    next_vertex = start
    while next_vertex != end:
        next_vertex = p[next_vertex, end]
        path.append(next_vertex)
    return path
    
        

d = np.array((
    (0, 2, np.inf, 3, 1, np.inf, np.inf, 10),
    (2, 0, 4, np.inf, np.inf, np.inf, np.inf, np.inf),
    (np.inf, 4, 0, np.inf, np.inf, np.inf, np.inf, 3),
    (3, np.inf, np.inf, 0, np.inf, np.inf, np.inf, 8), 
    (1, np.inf, np.inf, np.inf, 0, 2, np.inf, np.inf),
    (np.inf, np.inf, np.inf, np.inf, 2, 0, 3, np.inf),
    (np.inf, np.inf, np.inf, np.inf, np.inf, 3, 0, 1),
    (10, np.inf, 3, 8, np.inf, np.inf, 1, 0)
))
n = len(d)
p = np.array([[j for j in range(n)] for i in range(n)])
for k in range(n):   
    for i in range(n):
        for j in range(n):
            v = d[i][k] + d[k][j]
            if v < d[i][j]:
                d[i][j] = v
                p[i][j] = p[i][k]
print(p)                
find_path(p, 0, 7)

[[0 1 1 3 4 4 4 4]
 [0 1 2 0 0 0 0 2]
 [1 1 2 1 1 7 7 7]
 [0 0 0 3 0 0 0 7]
 [0 0 0 0 4 5 5 5]
 [4 4 6 4 4 5 6 6]
 [5 5 7 5 5 5 6 7]
 [6 2 2 3 6 6 6 7]]


[0, 4, 5, 6, 7]

Алгоритм Форда-Фалкерсона

In [ ]:
import math


def get_max_vertex(k, V, S):
    m = 0   # наименьшее допустимое значение
    v = -1
    for i, w in enumerate(V[k]):
        if i in S:
            continue

        if w[2] == 1:   # движение по стрелке
            if m < w[0]:
                m = w[0]
                v = i
        else:           # движение против стрелки
            if m < w[1]:
                m = w[1]
                v = i

    return v


def get_max_flow(T):
    w = [x[0] for x in T]
    return min(*w)


def updateV(V, T, f):
    for t in T:
        if t[1] == -1:  # это исток
            continue

        sgn = V[t[2]][t[1]][2]  # направление движения

        # меняем веса в таблице для (i,j) и (j,i)
        V[t[1]][t[2]][0] -= f * sgn
        V[t[1]][t[2]][1] += f * sgn

        V[t[2]][t[1]][0] -= f * sgn
        V[t[2]][t[1]][1] += f * sgn


V = [[[0,0,1], [20,0,1], [30,0,1], [10,0,1], [0,0,1]],
     [[20,0,-1], [0,0,1], [40,0,1], [0,0,1], [30,0,1]],
     [[30,0,-1], [40,0,-1], [0,0,1], [10,0,1], [20,0,1]],
     [[10,0,-1], [0,0,1], [10,0,-1], [0,0,1], [20,0,1]],
     [[0,0,1], [30,0,-1], [20,0,-1], [20,0,-1], [0,0,1]],
]

N = len(V)  # число вершин в графе
init = 0    # вершина истока (нумерация с нуля)
end = 4     # вершина стока
Tinit = (math.inf, -1, init)      # первая метка маршруто (a, from, vertex)
f = []      # максимальные потоки найденных маршрутов

j = init
while j != -1:
    k = init  # стартовая вершина (нумерация с нуля)
    T = [Tinit]  # метки маршрута
    S = {init}  # множество просмотренных вершин

    while k != end:     # пока не дошли до стока
        j = get_max_vertex(k, V, S)  # выбираем вершину с наибольшей пропускной способностью
        if j == -1:         # если следующих вершин нет
            if k == init:      # и мы на истоке, то
                break          # завершаем поиск маршрутов
            else:           # иначе, переходим к предыдущей вершине
                k = T.pop()[2]
                continue

        c = V[k][j][0] if V[k][j][2] == 1 else V[k][j][1]   # определяем текущий поток
        T.append((c, j, k))    # добавляем метку маршрута
        S.add(j)            # запоминаем вершину как просмотренную

        if j == end:    # если дошди до стока
            f.append(get_max_flow(T))     # находим максимальную пропускную способность маршрута
            updateV(V, T, f[-1])        # обновляем веса дуг
            break

        k = j

F = sum(f)
print(f"Максимальный поток равен: {F}")

Алгоритм Краскала

  1. сортируем ребра по возрастанию  
2. перебираем ребра с минимального ребра и соединяем вершины,    
которые не участвуют в группах  
3. когда не осталось вершина без групп, то перебираем оставшиеся ребра и   
и соединяем минимальным ребром несоединенные группы.

плохой вариант, без словаря  
ниже правильный вариант

In [43]:
# список ребер графа (длинаб вершина 1, вершина 2)
ribs = [(13, 1, 2), (18, 1, 3), (14, 1, 5), (22, 1, 6), (17, 1, 4)
    , (26, 2, 3), (22, 2, 5), (3, 3, 4), (19, 4, 6)]
sort_ribs = sorted(ribs, key=lambda x: x[0])
used_ribs = set()
used_vertex = set()
groups = []
n_vertex = 6
# первый этап ищем группы
for r in sort_ribs:
    # print('cur rib = ', r)
    if r in used_ribs:
        continue
    if r[1] in used_vertex and r[2] in used_vertex:
        continue
    used_ribs.add(r)
    used_vertex.add(r[1])
    used_vertex.add(r[2])
    for g in groups:
        if r[1] in g:
            g.add(r[2])
            break
        elif r[2] in g:
            g.add(r[1])
            break
    else:               
        group = set()
        group.add(r[1])
        group.add(r[2])
        groups.append(group)
    # print('used_ribs = ', used_ribs)
    # print('groups = ', groups)
    # print('---')
 # второй этап ищем остов (соединяем группы одним минимальным ребром)   
for r in sort_ribs:
    if r in used_ribs:
        continue    
    # print('cur rib = ', r)
    used_ribs.add(r)
    new_group = set()
    index_for_delete_group = []
    for i, g in enumerate(groups):
        if r[1] in g and r[2] in g:
            break
        else:
            new_group.update(g)
            # print('g = ', g)
            # print('new_group = ', new_group)  
            index_for_delete_group.append(i)
    if len(new_group) == n_vertex:
        break            
    # print('index_for_delete_group = ', index_for_delete_group)            
    del groups[index_for_delete_group[0]]            
    del groups[index_for_delete_group[1] - 1]            
    groups.append(new_group)      
    # print('groups = ', groups)
print('used_ribs = ', used_ribs)
    
    

used_ribs =  {(17, 1, 4), (19, 4, 6), (14, 1, 5), (3, 3, 4), (13, 1, 2)}


вариант со словарем

In [3]:
# список ребер графа (длинаб вершина 1, вершина 2)
ribs = [(13, 1, 2), (18, 1, 3), (14, 1, 5), (22, 1, 6), (17, 1, 4)
    , (26, 2, 3), (22, 2, 5), (3, 3, 4), (19, 4, 6)]
sort_ribs = sorted(ribs, key=lambda x: x[0])
used_ribs = []
groups = {}
# первый этап ищем группы
for r in sort_ribs:
    if r[1] not in groups or r[2] not in groups:
        if r[1] not in groups and r[2] not in groups:
            groups[r[1]] = {r[1], r[2]}
            groups[r[2]] = groups[r[1]]
        else:
            if r[1] not in groups:
                groups[r[2]].add(r[1])
                groups[r[1]] = groups[r[2]]
            if r[2] not in groups:
                groups[r[1]].add(r[2])
                groups[r[2]] = groups[r[1]]                
        used_ribs.append(r)              
        
  # второй этап ищем остов (соединяем группы одним минимальным ребром)  
  
for r in sort_ribs:         
    if r[1] not in groups[r[2]]:
        groups[r[2]].update(groups[r[1]])
        groups[r[1]] = groups[r[2]]
        used_ribs.append(r)   
used_ribs            
        
        
        
        

[(3, 3, 4), (13, 1, 2), (14, 1, 5), (19, 4, 6), (17, 1, 4)]

Алгоритм Прима (ближайшего соседа)

In [1]:
import numpy as np

def get_min_rib(ribs, used_vertex):
    min_rib = (np.inf, -1, -1)
    for v in used_vertex:
        cur_min_rib = min(ribs, key= lambda x: x[0] if (v == x[1] or v == x[2]) and (x[1] not in used_vertex or x[2] not in used_vertex) else np.inf)
        # print('v = ', v)
        # print('nim_rib = ', min_rib)
        # print('cur_min_rib = ', cur_min_rib)
        if cur_min_rib[0] < min_rib[0]:
            min_rib = cur_min_rib

    return min_rib

ribs = [(np.inf, -1, -1), (13, 1, 2), (18, 1, 3), (17, 1, 4), (14, 1, 5), (22, 1, 6),
     (26, 2, 3), (19, 2, 5), (30, 3, 4), (22, 4, 6)]
n = 6
used_vertex = {1}
used_ribs = []

while len(used_vertex) < n:
    min_rib = get_min_rib(ribs, used_vertex)          
    if min_rib[0] == np.inf:
        break
    used_vertex.add(min_rib[1])
    used_vertex.add(min_rib[2])
    used_ribs.append(min_rib)
used_ribs    

[(13, 1, 2), (14, 1, 5), (17, 1, 4), (18, 1, 3), (22, 1, 6)]

Сортировка выбором (сложность = О(n*n))

In [5]:
l = [8, -2, 1, 0, -3, 4, -9]
len_ = len(l)
for i in range(len_-1):
    min_el = l[i]
    min_index = i
    for j in range(i+1, len_):
        if l[j] < min_el:
            min_el = l[j]
            min_index = j
    if min_index != i:
        l[i], l[min_index] = l[min_index], l[i]
        
l        

[-9, -3, -2, 0, 1, 4, 8]

Сортировка вставками

In [5]:
l = [8, -2, 1, 0, -3, 4, -9]
n =len(l)
for i in range(1, n):
    for j in range(i, 0, -1):
        if l[j-1] > l[j]:
            l[j-1], l[j] = l[j], l[j-1]
        else:
            break
l            

[-9, -3, -2, 0, 1, 4, 8]

Сортировка пузырьком

In [ ]:
l = [8, -2, 1, 0, -3, 4, -9]
n = len(l)
for i in range(n-1, -1, -1):
    for j in range(i):
        if l[j] > l[j+1]:
            l[j], l[j+1] = l[j+1], l[j]
l            

или

In [5]:
l = [8, -2, 1, 0, -3, 4, -9]
n = len(l)
for i in range(n-1):
    for j in range(n-i-1):
        if l[j] > l[j+1]:
            l[j+1], l[j] = l[j], l[j+1]
l            

[-9, -3, -2, 0, 1, 4, 8]

Слияние двух упорядоченных списков

In [16]:
a = [1,2,3,4,5]
b = [1,4,5,6,8,10,11,20]
N = len(a)
M = len(b)
i = 0
j = 0
c = []
while i < N and j < M:
    if a[i] == b[j]:
        c.append(a[i])
        c.append(b[j])
        i += 1
        j += 1
    elif a[i] < b[j]:
        c.append(a[i])
        i += 1
    elif a[i] > b[j]:
        c.append(b[j])
        j += 1        
c += b[j:]  
c += a[i:]       
c 

[1, 1, 2, 3, 4, 4, 5, 5, 6, 8, 10, 11, 20]

Merge sort  
Быстрая сортировка слиянием

In [12]:
l = [8, -2, 1, 0, -3, 4, -9]

def merge_list(a, b):
    N = len(a)
    M = len(b)
    i = 0
    j = 0
    c = []
    while i < N and j < M:
        if a[i] == b[j]:
            c.append(a[i])
            c.append(b[j])
            i += 1
            j += 1
        elif a[i] < b[j]:
            c.append(a[i])
            i += 1
        elif a[i] > b[j]:
            c.append(b[j])
            j += 1        
    c += b[j:]  
    c += a[i:]  
    return c  

def merge_sort(l):
    if len(l) == 1:
        return l
    n = len(l) // 2
    l1 = merge_sort(l[:n])
    l2 = merge_sort(l[n:])
    return merge_list(l1, l2)

merge_sort(l)    
    
    

[-9, -3, -2, 0, 1, 4, 8]

Quick sort   
Быстрая сортировка (также Хоара)

In [5]:
# используя дополнительные списки
import random 

l = [8, -2, 1, 0, -3, 4, -9]

def hoara_sort(l):
    len_l = len(l)
    if len_l <= 1:
        return l
    random_el = random.choice(l)
    under_el = [el for el in l if el < random_el]
    equal_el = [el for el in l if el == random_el]
    upper_el = [el for el in l if el > random_el]
    return hoara_sort(under_el) + equal_el + hoara_sort(upper_el)

hoara_sort(l)

[-9, -3, -2, 0, 1, 4, 8]

 - случайно выбираем индекс от левой границы до правой
- ставим элемент с этим индексом на левую границу (в начало отрезка)
- запоминаем первый элемент в x для удобства
- j ставим на левую границу
- далее идем от левой границы до правой в цикле по i
- если i - й элемент меньше x (первого элемента),  
то j увеличиваем на 1 и меняем местами i и j элементы
- в конце меняем местами j и left, чтобы наш элемент (с выбранным случайным индексом встал на место)

In [4]:
# сортировка на месте
# экономит памятЬ, так как не нужно выделять память на новые списки
from random import randint

l = [-2, 2, 1, 1, 1, 1, -9]

def partition(array: list, left: int, right: int) -> int:
    rand = randint(left, right)
    array[rand], array[left] = array[left], array[rand]
    x = array[left]
    j = left
    for i in range(left + 1, right + 1):
        if array[i] <= x: 
            j += 1
            array[j], array[i] = array[i], array[j]
    array[left], array[j] = array[j], array[left]
    return j


def quick_sort_inplace(array: list, left: int, right: int) -> None:
    if left < right:
        m = partition(array, left, right)
        quick_sort_inplace(array, left, m - 1)
        quick_sort_inplace(array, m + 1, right)
quick_sort_inplace(l, 0, len(l)-1)     
l  

[-9, -2, 1, 1, 1, 1, 2]

Проверка правильности последоваетльности скобок  
(([])) - верно
(([]) - неверно

In [15]:
s = '(2+5)*([(10+4)]-7)'
s_stack = []
d = {'(': ')', '[': ']', '{': '}'}
keys = d.keys()
values = d.values()
stop = 0
for el in s:
    if el in keys:
        s_stack.append(el)
    elif el in values:
        if len(s_stack) == 0:
            stop = 1
            break          
        prev = s_stack.pop()
        if el != d[prev]:
            stop = 1
            break
            
if stop:
    print('Нверно')
else:
    print('Верно')
    

Нверно


Алгоритм бинарного поиска

In [22]:
def bi_sort(l, w, left, right):
    middle = (right + left) // 2
    if right - left < 2:
        return -1
    if w == l[middle]:
        return middle
    if w > l[middle]:
        return bi_sort(l, w, middle, right)
    else:
        return bi_sort(l, w, left, middle)
        

l = ['acorn', 'apple', 'bite', 'bold', 'cot', 'dull', 'feel', 'fund', 'mine', 'morn']
w = 'cite'
bi_sort(l, w, 0, len(l)-1)

-1